package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List<String> _jspx_dependants;

  private org.glassfish.jsp.api.ResourceInjector _jspx_resourceInjector;

  public java.util.List<String> getDependants() {
    return _jspx_dependants;
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;

    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;
      _jspx_resourceInjector = (org.glassfish.jsp.api.ResourceInjector) application.getAttribute("com.sun.appserv.jsp.resource.injector");

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("    <head>\n");
      out.write("        <title>Fake News Detection</title>\n");
      out.write("        \n");
      out.write("        \n");
      out.write("        \n");
      out.write("        <!-- custom-theme -->\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\n");
      out.write("        <meta name=\"keywords\" content=\"Mastering Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template, \n");
      out.write("              Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design\" />\n");
      out.write("        <script type=\"application/x-javascript\"> addEventListener(\"load\", function() { setTimeout(hideURLbar, 0); }, false);\n");
      out.write("            function hideURLbar(){ window.scrollTo(0,1); } </script>\n");
      out.write("        <!-- //custom-theme -->\n");
      out.write("        <link href=\"css/bootstrap.css\" rel=\"stylesheet\" type=\"text/css\" media=\"all\" />\n");
      out.write("        <link href=\"css/JiSlider.css\" rel=\"stylesheet\"> \n");
      out.write("        <link rel=\"stylesheet\" href=\"css/flexslider.css\" type=\"text/css\" media=\"screen\" property=\"\" />\n");
      out.write("\n");
      out.write("        <link href=\"css/style.css\" rel=\"stylesheet\" type=\"text/css\" media=\"all\" />\n");
      out.write("\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/flexslider.css\" type=\"text/css\" media=\"screen\" property=\"\" />\n");
      out.write("        <!-- font-awesome-icons -->\n");
      out.write("        <link href=\"css/font-awesome.css\" rel=\"stylesheet\"> \n");
      out.write("        <!-- //font-awesome-icons -->\n");
      out.write("        <link href=\"//fonts.googleapis.com/css?family=Raleway:400,400i,500,500i,600,600i,700,700i,800\" rel=\"stylesheet\">\n");
      out.write("        <link href='//fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600,600italic,700,700italic,800,800italic' rel='stylesheet' type='text/css'>\n");
      out.write("    </head>\n");
      out.write("\n");
      out.write("    <body>\n");
      out.write("        <!-- banner -->\n");
      out.write("        <div class=\"main_section_agile\">\n");
      out.write("            <div class=\"w3_agile_banner_top\">\n");
      out.write("                <div class=\"agile_phone_mail\">\n");
      out.write("                    <ul class=\"agile_forms\">\n");
      out.write("                    </ul>\n");
      out.write("                    <ul>\n");
      out.write("                        <li><i class=\"fa fa-phone\" aria-hidden=\"true\"></i>+91 7057163018</li>\n");
      out.write("                        <!-- <li><a href=\"https://twitter.com/piyusha1012\" ><i class=\"fa fa-twitter\" aria-hidden=\"true\"></i></a></li> -->\n");
      out.write("                        <li><i class=\"fa fa-envelope\" aria-hidden=\"true\"></i><a href=\"https://mail.google.com/mail/u/0/#inbox?compose=new\">kartikigangthade@gmail.com</a></li>\n");
      out.write("                    </ul>\n");
      out.write("                    <div class=\"clearfix\"> </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"agileits_w3layouts_banner_nav\">\n");
      out.write("                <nav class=\"navbar navbar-default\">\n");
      out.write("                    <div class=\"navbar-header navbar-left\">\n");
      out.write("                        <button type=\"button\" class=\"navbar-toggle collapsed\" data-toggle=\"collapse\" data-target=\"#bs-example-navbar-collapse-1\">\n");
      out.write("                            <span class=\"sr-only\">Toggle navigation</span>\n");
      out.write("                            <span class=\"icon-bar\"></span>\n");
      out.write("                            <span class=\"icon-bar\"></span>\n");
      out.write("                            <span class=\"icon-bar\"></span>\n");
      out.write("                        </button>\n");
      out.write("                        <h1><a class=\"navbar-brand\" href=\"index.jsp\"><i>Fake</i><span> News Detection</span></a></h1>\n");
      out.write("                    </div>\n");
      out.write("                    <!-- Collect the nav links, forms, and other content for toggling -->\n");
      out.write("                    <div class=\"collapse navbar-collapse navbar-right\" id=\"bs-example-navbar-collapse-1\">\n");
      out.write("                        <nav class=\"menu--iris\">\n");
      out.write("                            <ul class=\"nav navbar-nav menu__list\">\n");
      out.write("                                <li class=\"menu__item menu__item--current\"><a href=\"index.jsp\" class=\"menu__link\">Home</a></li>\n");
      out.write("                                <li><a class=\"active\" href=\"#\" data-toggle=\"modal\" data-target=\"#myModal2\"><i class=\"fa fa-sign-in\" aria-hidden=\"true\"></i> Admin Login</a> </li>\n");
      out.write("                                <li><a class=\"active\" href=\"#\" data-toggle=\"modal\" data-target=\"#myModal3\"><i class=\"fa fa-sign-in\" aria-hidden=\"true\"></i> user Login</a></li>\n");
      out.write("                                <li><a href=\"#\" data-toggle=\"modal\" data-target=\"#myModal5\"><i class=\"fa fa-pencil-square-o\" aria-hidden=\"true\"></i> User Registration</a> </li>\n");
      out.write("                            </ul>\n");
      out.write("                        </nav>\n");
      out.write("                    </div>\n");
      out.write("                </nav>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <!-- banner -->\n");
      out.write("        <div class=\"banner-silder\">\n");
      out.write("            <div id=\"JiSlider\" class=\"jislider\">\n");
      out.write("                <ul>\n");
      out.write("                    <li>\n");
      out.write("                        <div class=\"w3layouts-banner-top\">\n");
      out.write("\n");
      out.write("                            <div class=\"container\">\n");
      out.write("                                \t\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </li>\n");
      out.write("                    <li>\n");
      out.write("                        <div class=\"w3layouts-banner-top w3layouts-banner-top1\">\n");
      out.write("                            <div class=\"container\">\n");
      out.write("                                \t\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </li>\n");
      out.write("                    <li>\n");
      out.write("                        <div class=\"w3layouts-banner-top w3layouts-banner-top2\">\n");
      out.write("                            <div class=\"container\">\n");
      out.write("                                \t\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </li>\n");
      out.write("\n");
      out.write("                </ul>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <!-- //banner -->\n");
      out.write("        <!-- Modal1 -->\n");
      out.write("        <div class=\"modal fade\" id=\"myModal2\" tabindex=\"-1\" role=\"dialog\">\n");
      out.write("            <div class=\"modal-dialog\">\n");
      out.write("                <!-- Modal content-->\n");
      out.write("                <div class=\"modal-content\">\n");
      out.write("                    <div class=\"modal-header\">\n");
      out.write("                        <button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\n");
      out.write("\n");
      out.write("                        <div class=\"signin-form profile\">\n");
      out.write("                            <h3 class=\"agileinfo_sign\">Admin Login</h3>\t\n");
      out.write("                            <div class=\"login-form\">\n");
      out.write("                                <form action=\"AdminLogin\" method=\"post\" autocomplete=\"off\">\n");
      out.write("                                    <input type=\"text\" name=\"name\" placeholder=\"Admin Name\" required=\"\">\n");
      out.write("                                    <input type=\"password\" name=\"pass\" placeholder=\"Password\" required=\"\">\n");
      out.write("                                    <div class=\"tp\">\n");
      out.write("                                        <input type=\"submit\" value=\"Sign In\">\n");
      out.write("                                        <input type=\"reset\" value=\"Reset\">\n");
      out.write("                                    </div>\n");
      out.write("                                </form>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"modal fade\" id=\"myModal3\" tabindex=\"-1\" role=\"dialog\">\n");
      out.write("            <div class=\"modal-dialog\">\n");
      out.write("                <!-- Modal content-->\n");
      out.write("                <div class=\"modal-content\">\n");
      out.write("                    <div class=\"modal-header\">\n");
      out.write("                        <button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\n");
      out.write("\n");
      out.write("                        <div class=\"signin-form profile\">\n");
      out.write("                            <h3 class=\"agileinfo_sign\">User Login</h3>\t\n");
      out.write("                            <div class=\"login-form\">\n");
      out.write("                                <form action=\"UserLogin\" method=\"post\" autocomplete=\"off\">\n");
      out.write("                                    <input type=\"text\" name=\"uname\" placeholder=\"Username\" required=\"\">\n");
      out.write("                                    <input type=\"password\" name=\"pass\" placeholder=\"Password\" required=\"\">\n");
      out.write("                                    <div class=\"tp\">\n");
      out.write("                                        <input type=\"submit\" value=\"Sign In\">\n");
      out.write("                                        <input type=\"reset\" value=\"Reset\">\n");
      out.write("                                    </div>\n");
      out.write("                                </form>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"login-social-grids\">\n");
      out.write("                                <ul>\n");
      out.write("                                    <li><a href=\"#\"><i class=\"fa fa-facebook\" ></i></a></li>\n");
      out.write("                           \n");
      out.write("                                    <li><a href=\"https://twitter.com/piyusha1012\"><i class=\"fa fa-twitter\"></i></a></li>\n");
      out.write("                                  <li><a href=\"#\"><i class=\"fa fa-rss\"></i></a></li> \n");
      out.write("                                </ul>\n");
      out.write("                            </div>\n");
      out.write("                            <p><a href=\"#\" data-toggle=\"modal\" data-target=\"#myModa21\" > Forgot Password?</a></p>\n");
      out.write("                            <p><a href=\"#\" data-toggle=\"modal\" data-target=\"#myModal5\" > Don't have an account?</a></p>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"modal fade\" id=\"myModa21\" tabindex=\"-1\" role=\"dialog\">\n");
      out.write("            <div class=\"modal-dialog\">\n");
      out.write("                <!-- Modal content-->\n");
      out.write("                <div class=\"modal-content\">\n");
      out.write("                    <div class=\"modal-header\">\n");
      out.write("                        <button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\n");
      out.write("\n");
      out.write("                        <div class=\"signin-form profile\">\n");
      out.write("                            <h3 class=\"agileinfo_sign\">Forgot Password</h3>\t\n");
      out.write("                            <div class=\"login-form\">\n");
      out.write("                                <form action=\"SendOTP\" method=\"post\">\n");
      out.write("                                    <input type=\"email\" name=\"email\" placeholder=\"Please Enter Mail Address\" required=\"\">\n");
      out.write("                                    <div class=\"tp\">\n");
      out.write("                                        <input type=\"submit\" value=\"Submit\">\n");
      out.write("                                        <input type=\"reset\" value=\"Reset\">\n");
      out.write("                                    </div>\n");
      out.write("                                </form>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("        <div class=\"modal fade\" id=\"myModal5\" tabindex=\"-1\" role=\"dialog\">\n");
      out.write("            <div class=\"modal-dialog\">\n");
      out.write("                <!-- Modal content-->\n");
      out.write("                <div class=\"modal-content\">\n");
      out.write("                    <div class=\"modal-header\">\n");
      out.write("                        <button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\n");
      out.write("                        <div class=\"signin-form profile\">\n");
      out.write("                            <h3 class=\"agileinfo_sign\">User Registration</h3>\t\n");
      out.write("                            <div class=\"login-form\">\n");
      out.write("                                <form action=\"Reg\" method=\"post\" autocomplete=\"off\">\n");
      out.write("                                    <input type=\"text\" name=\"fname\" placeholder=\"First Name\" required=\"\" title=\"Enter Valid First Name\" >\n");
      out.write("                                    <input type=\"text\" name=\"lname\" placeholder=\"Last Name\" required=\"\" title=\"Enter Valid Last Name\">\n");
      out.write("                                    <input type=\"email\" name=\"email\" placeholder=\"Email\" required pattern=\"[a-z]+.[a-z0-9._%+-]+@[a-z0-9.-]+\\.[a-z]{2,4}$\" title=\"Enter Valid Email Address.\">\n");
      out.write("                                    <input type=\"text\" name=\"mob\" placeholder=\"Mobile Number\" required pattern=\"[7-9]{1}[0-9]{9}\" title=\"Enter valid 10 digit Phone Number\">\n");
      out.write("                                    <input type=\"text\" name=\"tid\" placeholder=\"Twitter Id\" required=\"\" title=\"It's not neccesary to have a Twitter Account\"> \n");
      out.write("                                    <input type=\"text\" name=\"username\" placeholder=\"Username\" required=\"\">\n");
      out.write("                                    <input type=\"password\" name=\"pass\" placeholder=\"Password\" required pattern=\"(?=.*\\d)(?=.*[a-z])(?=.*[A-Z]).{6,}\" title=\"Password must contain at least 6 characters, including Upper and Lowercase and Numbers.\">\n");
      out.write("                                    <input type=\"submit\" value=\"Sign Up\">\n");
      out.write("                                    <input type=\"reset\" value=\"Reset\">\n");
      out.write("                                </form>\n");
      out.write("                            </div> \n");
      out.write("                            <p><a href=\"#\"> By clicking register, I agree to your terms</a></p>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("        <div class=\"modal video-modal fade\" id=\"myModal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"myModal\">\n");
      out.write("            <div class=\"modal-dialog\" role=\"document\">\n");
      out.write("                <div class=\"modal-content\">\n");
      out.write("\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <!-- //bootstrap-pop-up -->\n");
      out.write("        <!-- banner-bottom --><br><br>\n");
      out.write("        <h3 class=\"w3l_header w3_agileits_header\">INTRODUCTION <span></span></h3><br><br>\n");
      out.write("        \n");
      out.write("        <p align=\"justify\">\n");
      out.write("             Twitter has emerged as a major micro-blogging website, having over 100 million users generating over 500 million tweets every day. With such large audience, Twitter has consistently attracted users to convey their opinions and perspective about any issue, brand, company or any other topic of interest. Due to this reason, Twitter is used as an informative source by many organizations, institutions and companies. On Twitter, users are allowed to share their opinions in the form of tweets, using only 140 characters. This leads to people compacting their statements by using slang, abbreviations, emoticons, short forms etc. Along with this, people convey their opinions by using sarcasm and polysemy. Hence it is justified to term the Twitter language as unstructured. In order to extract sentiment from tweets, sentiment analysis is used. The results from this can be used in many areas like analyzing and monitoring changes of sentiment with an event, sentiments regarding a particular brand or release of a particular product, analyzing public view of government policies etc. \n");
      out.write("        </p><br>\n");
      out.write("       <p align=\"justify\">\n");
      out.write("            A lot of research has been done on Twitter data in order to classify the tweets and analyze the results. In this project we aim to predict the sentiments from tweets by checking the polarity of tweets as positive, negative or irrelevant. Sentiment analysis is a process of deriving sentiment of a particular statement or sentence. It's a classification technique which derives opinion from the tweets and formulates a sentiment and on the basis of which, sentiment classification is performed. Sentiments are subjective to the topic of interest. We are required to formulate that what kind of features will decide for the sentiment it embodies. In the programming model, sentiment we refer to, is class of entities that the person performing sentiment analysis wants to find in the tweets. Whereas machine learning approach involves use of feature extraction and training the model using feature set and some dataset. The basic steps for performing sentiment analysis includes data collection, pre-processing of data, feature extraction, selecting baseline features, sentiment detection and performing classification either using simple computation or else machine learning approaches. Features are like Parts-of speech features i.e. nouns, adverbs, adjectives, etc. in each tweets are tagged. \n");
      out.write("        </p><br>\n");
      out.write("        <p align=\"justify\">\n");
      out.write("            We for the accuracy purpose of polarity will be detecting sentiments along with various knowledge base patterns and multiple machine learning strategies to evaluate the sentiments. Alongside we will be checking if the tweet is genuine or not or if has influenced by other tweets which can be very useful in fake tweets mitigation on social medias. This approach will produce the higher accuracy for polarity by considering POS factor and genuineness as well as can be used in various sectors such as analyzing product reviews or government policies, etc. where it can be found if negative influence is spread and if it affects people.\n");
      out.write("        </p>\n");
      out.write("    \n");
      out.write("\n");
      out.write("       <!-- footer -->\n");
      out.write("       <br><br>\n");
      out.write("       \n");
      out.write("    <center>  <p><b> &copy 2020 Fake News Detection Project. All Rights Reserved.</b> <a href=\"https://.com/\" target=\"_blank\"></a></p></center>\n");
      out.write("\n");
      out.write("    <!-- //footer -->\n");
      out.write("    <!-- start-smoth-scrolling -->\n");
      out.write("    <!-- js -->\n");
      out.write("    <script type=\"text/javascript\" src=\"js/jquery-2.1.4.min.js\"></script>\n");
      out.write("    <!-- //js -->\n");
      out.write("    <script src=\"js/JiSlider.js\"></script>\n");
      out.write("    <script>\n");
      out.write("        $(window).load(function () {\n");
      out.write("            $('#JiSlider').JiSlider({color: '#fff', start: 3, reverse: true}).addClass('ff')\n");
      out.write("        })\n");
      out.write("    </script><script type=\"text/javascript\">\n");
      out.write("\n");
      out.write("        var _gaq = _gaq || [];\n");
      out.write("        _gaq.push(['_setAccount', 'UA-36251023-1']);\n");
      out.write("        _gaq.push(['_setDomainName', 'jqueryscript.net']);\n");
      out.write("        _gaq.push(['_trackPageview']);\n");
      out.write("\n");
      out.write("        (function () {\n");
      out.write("            var ga = document.createElement('script');\n");
      out.write("            ga.type = 'text/javascript';\n");
      out.write("            ga.async = true;\n");
      out.write("            ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';\n");
      out.write("            var s = document.getElementsByTagName('script')[0];\n");
      out.write("            s.parentNode.insertBefore(ga, s);\n");
      out.write("        })();\n");
      out.write("\n");
      out.write("    </script>\n");
      out.write("    <!-- stats -->\n");
      out.write("    <script src=\"js/jquery.waypoints.min.js\"></script>\n");
      out.write("    <script src=\"js/jquery.countup.js\"></script>\n");
      out.write("    <script>\n");
      out.write("        $('.counter').countUp();\n");
      out.write("    </script>\n");
      out.write("    <!-- //stats -->\n");
      out.write("    <!-- //footer -->\n");
      out.write("    <!-- flexSlider -->\n");
      out.write("    <script defer src=\"js/jquery.flexslider.js\"></script>\n");
      out.write("    <script type=\"text/javascript\">\n");
      out.write("        $(window).load(function () {\n");
      out.write("            $('.flexslider').flexslider({\n");
      out.write("                animation: \"slide\",\n");
      out.write("                start: function (slider) {\n");
      out.write("                    $('body').removeClass('loading');\n");
      out.write("                }\n");
      out.write("            });\n");
      out.write("        });\n");
      out.write("    </script>\n");
      out.write("    <!-- //flexSlider -->\n");
      out.write("\n");
      out.write("\n");
      out.write("    <script type=\"text/javascript\" src=\"js/move-top.js\"></script>\n");
      out.write("    <script type=\"text/javascript\" src=\"js/easing.js\"></script>\n");
      out.write("    <script type=\"text/javascript\">\n");
      out.write("        jQuery(document).ready(function ($) {\n");
      out.write("            $(\".scroll\").click(function (event) {\n");
      out.write("                event.preventDefault();\n");
      out.write("                $('html,body').animate({scrollTop: $(this.hash).offset().top}, 1000);\n");
      out.write("            });\n");
      out.write("        });\n");
      out.write("    </script>\n");
      out.write("    <!-- start-smoth-scrolling -->\n");
      out.write("    <!-- for bootstrap working -->\n");
      out.write("    <script src=\"js/bootstrap.js\"></script>\n");
      out.write("    <!-- //for bootstrap working -->\n");
      out.write("    <!-- here stars scrolling icon -->\n");
      out.write("    <script type=\"text/javascript\">\n");
      out.write("        $(document).ready(function () {\n");
      out.write("            /*\n");
      out.write("             var defaults = {\n");
      out.write("             containerID: 'toTop', // fading element id\n");
      out.write("             containerHoverID: 'toTopHover', // fading element hover id\n");
      out.write("             scrollSpeed: 1200,\n");
      out.write("             easingType: 'linear' \n");
      out.write("             };\n");
      out.write("             */\n");
      out.write("\n");
      out.write("            $().UItoTop({easingType: 'easeOutQuart'});\n");
      out.write("\n");
      out.write("        });\n");
      out.write("    </script>\n");
      out.write("    <!-- //here ends scrolling icon -->\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          out.clearBuffer();
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
